run:
  go: '1.20'
  timeout: 5m
  tests: false

  skip-dirs:
  - utils

output:
  format: colored-line-number
  sort-results: true

linters-settings:
  errcheck:
    check-blank: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - wsl

  disable:
    - typecheck

severity:
  default-severity: error