run:
  go: '1.18'
  timeout: 5m
  tests: false

  skip-dirs:
  - utils

output:
  format: colored-line-number
  sort-results: true

linters-settings:
  errcheck:
    check-blank: true

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - wsl

severity:
  default-severity: error