ResourceFilePath = "resources/"

[DataService]
RemoteEndpoint = "http://127.0.0.1:11111"
BindIP = "0.0.0.0"
Port = 11111
LogHTTPRequest = true
LogInsertingHostdata = false
LogDataPatching = true
EnablePatching = true
AgentUsername = "user"
AgentPassword = "password"
LicenseTypeMetricsDefault = [ "Processor Perpetual", "Named User Plus Perpetual", "Stream Perpetual", "Computer Perpetual" ]

  [DataService.LicenseTypeMetricsByEnvironment]
  TEST = [ "Named User Plus Perpetual", "Processor Perpetual" ]

  [DataService.CurrentHostCleaningJob]
  Crontab = "@daily"
  HourThreshold = 8760
  RunAtStartup = false

  [DataService.ArchivedHostCleaningJob]
  Crontab = "@daily"
  HourThreshold = 8760
  RunAtStartup = false
  
  [DataService.FreshnessCheckJob]
  Crontab = "@daily"
  DaysThreshold = 1
  RunAtStartup = false

[AlertService]
RemoteEndpoint = "http://127.0.0.1:11112"
BindIP = "127.0.0.1"
Port = 11112
LogHTTPRequest = true
LogMessages = true
LogAlertThrows = true
PublisherUsername = "publisher"
PublisherPassword = "r4nd0mS3cR3tp4ssW0rd"
QueueBufferSize = 10240

[APIService]
RemoteEndpoint = "http://127.0.0.1:11113"
BindIP = "0.0.0.0"
Port = 11113
LogHTTPRequest = true
ReadOnly = false
EnableInsertingCustomPatchingFunction = true
DebugOracleDatabaseAgreementsAssignmentAlgorithm = false
DefaultDatabaseTags = [
  "coolest",
  "very important",
  "gdpr-compliant"
]

  [APIService.AuthenticationProvider]
  Type = "basic"
  Username = "user"
  Password = "password"
  PrivateKey = "/path/to/my_private_rsa_key"
  PublicKey = "/path/to/my_public_rsa_key.pub"
  TokenValidityTimeout = 7200

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^Red Hat Enterprise Linux 8.*$"
  Group = "RHEL8"
  Product = "RedHat/EnterpriseLinux8"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^Red Hat Enterprise Linux 7.*$"
  Group = "RHEL7"
  Product = "RedHat/EnterpriseLinux7"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^Red Hat Enterprise Linux 6.*$"
  Group = "RHEL6"
  Product = "RedHat/EnterpriseLinux6"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^Red Hat Enterprise Linux 5.*$"
  Group = "RHEL5"
  Product = "RedHat/EnterpriseLinux5"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^HPUX.*$"
  Group = "HPUX"
  Product = "HP/HPUX"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^AIX.*$"
  Group = "AIX"
  Product = "IBM/AIX"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^Solaris .*$"
  Group = "Solaris"
  Product = "Oracle/Solaris"


[ChartService]
RemoteEndpoint = "http://127.0.0.1:11116"
BindIP = "0.0.0.0"
Port = 11116
LogHTTPRequest = true

[RepoService]
DistributedFiles = "distributed_files/"

  [RepoService.HTTP]
  Enable = true
  RemoteEndpoint = "http://127.0.0.1:11114"
  BindIP = "0.0.0.0"
  Port = 11114
  LogHTTPRequest = true

  [[RepoService.UpstreamRepositories]]
  Name = "ercole-io"
  Type = "ercole-reposervice"
  URL = "https://repository.ercole.io"

[Mongodb]
URI = "mongodb://localhost:27017/ercole"
DBName = "ercole"
Migrate = true
