// Copyright (c) 2020 Sorint.lab S.p.A.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package repo

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestSortArtifactInfo(t *testing.T) {
	expected := Index{
		&ArtifactInfo{},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.11", ReleaseDate: "2020-03-27", Filename: "ercole-agent-1.6.11-1.el6.x86_64.rpm", Name: "ercole-agent-rhel6", OperatingSystemFamily: "rhel", OperatingSystem: "rhel6", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.11/ercole-agent-1.6.11-1.el6.x86_64.rpm"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.12", ReleaseDate: "2020-06-08", Filename: "ercole-agent-1.6.12-1.el6.x86_64.rpm", Name: "ercole-agent-rhel6", OperatingSystemFamily: "rhel", OperatingSystem: "rhel6", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.12/ercole-agent-1.6.12-1.el6.x86_64.rpm"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.11", ReleaseDate: "2020-03-27", Filename: "ercole-agent-1.6.11-1.el7.x86_64.rpm", Name: "ercole-agent-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.11/ercole-agent-1.6.11-1.el7.x86_64.rpm"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.12", ReleaseDate: "2020-06-08", Filename: "ercole-agent-1.6.12-1.el7.x86_64.rpm", Name: "ercole-agent-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.12/ercole-agent-1.6.12-1.el7.x86_64.rpm"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.11", ReleaseDate: "2020-03-27", Filename: "ercole-agent-setup-1.6.11.exe", Name: "ercole-agent-win", OperatingSystemFamily: "win", OperatingSystem: "win", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.11/ercole-agent-setup-1.6.11.exe"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.12", ReleaseDate: "2020-06-08", Filename: "ercole-agent-setup-1.6.12.exe", Name: "ercole-agent-win", OperatingSystemFamily: "win", OperatingSystem: "win", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.12/ercole-agent-setup-1.6.12.exe"}},
		{Repository: "ercole-agent-aix", Installed: false, Version: "1.6.0", ReleaseDate: "2019-10-21", Filename: "ercole-agent-aix-1.6.0-1.aix6.1.noarch.rpm", Name: "ercole-agent-aix", OperatingSystemFamily: "aix", OperatingSystem: "aix6.1", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-aix/releases/download/1.6.0/ercole-agent-aix-1.6.0-1.aix6.1.noarch.rpm"}},
		{Repository: "ercole-agent-aix", Installed: false, Version: "1.6.8", ReleaseDate: "2020-03-19", Filename: "ercole-agent-aix-1.6.8-1.aix6.1.noarch.rpm", Name: "ercole-agent-aix", OperatingSystemFamily: "aix", OperatingSystem: "aix6.1", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-aix/releases/download/1.6.8/ercole-agent-aix-1.6.8-1.aix6.1.noarch.rpm"}},
		{Repository: "ercole-agent-aix", Installed: false, Version: "1.6.7", ReleaseDate: "2020-01-31", Filename: "ercole-agent-aix-1.6.7.tar.gz", Name: "ercole-agent-aix-targz", OperatingSystemFamily: "aix-tar-gz", OperatingSystem: "aix6.1", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-aix/releases/download/1.6.7/ercole-agent-aix-1.6.7.tar.gz"}},
		{Repository: "ercole-agent-aix", Installed: false, Version: "1.6.8", ReleaseDate: "2020-03-19", Filename: "ercole-agent-aix-1.6.8.tar.gz", Name: "ercole-agent-aix-targz", OperatingSystemFamily: "aix-tar-gz", OperatingSystem: "aix6.1", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-aix/releases/download/1.6.8/ercole-agent-aix-1.6.8.tar.gz"}},
		{Repository: "ercole-agent-exadata", Installed: false, Version: "1.6.2", ReleaseDate: "2020-01-31", Filename: "ercole-agent-exadata-1.6.2-1.el6.x86_64.rpm", Name: "ercole-agent-exadata-rhel6", OperatingSystemFamily: "rhel", OperatingSystem: "rhel6", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-exadata/releases/download/1.6.2/ercole-agent-exadata-1.6.2-1.el6.x86_64.rpm"}},
		{Repository: "ercole-agent-exadata", Installed: false, Version: "1.6.3", ReleaseDate: "2020-03-19", Filename: "ercole-agent-exadata-1.6.3-1.el6.x86_64.rpm", Name: "ercole-agent-exadata-rhel6", OperatingSystemFamily: "rhel", OperatingSystem: "rhel6", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-exadata/releases/download/1.6.3/ercole-agent-exadata-1.6.3-1.el6.x86_64.rpm"}},
		{Repository: "ercole-agent-exadata", Installed: false, Version: "1.6.2", ReleaseDate: "2020-01-31", Filename: "ercole-agent-exadata-1.6.2-1.el7.x86_64.rpm", Name: "ercole-agent-exadata-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-exadata/releases/download/1.6.2/ercole-agent-exadata-1.6.2-1.el7.x86_64.rpm"}},
		{Repository: "ercole-agent-exadata", Installed: false, Version: "1.6.3", ReleaseDate: "2020-03-19", Filename: "ercole-agent-exadata-1.6.3-1.el7.x86_64.rpm", Name: "ercole-agent-exadata-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-exadata/releases/download/1.6.3/ercole-agent-exadata-1.6.3-1.el7.x86_64.rpm"}},
		{Repository: "ercole-agent-hpux", Installed: false, Version: "1.6.4", ReleaseDate: "2019-12-16", Filename: "ercole-agent-hpux-1.6.4.tar.gz", Name: "ercole-agent-hpux", OperatingSystemFamily: "hpux", OperatingSystem: "hpux", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-hpux/releases/download/1.6.4/ercole-agent-hpux-1.6.4.tar.gz"}},
		{Repository: "ercole-agent-hpux", Installed: false, Version: "1.6.5", ReleaseDate: "2020-01-14", Filename: "ercole-agent-hpux-1.6.5.tar.gz", Name: "ercole-agent-hpux", OperatingSystemFamily: "hpux", OperatingSystem: "hpux", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-hpux/releases/download/1.6.5/ercole-agent-hpux-1.6.5.tar.gz"}},
		{Repository: "ercole-agent-rhel5", Installed: false, Version: "1.6.8", ReleaseDate: "2020-07-28", Filename: "ercole-agent-1.6.8-1.x86_64.rpm", Name: "ercole-agent-rhel5", OperatingSystemFamily: "rhel", OperatingSystem: "rhel5", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-rhel5/releases/download/1.6.8/ercole-agent-1.6.8-1.x86_64.rpm"}},
		{Repository: "ercole-agent-rhel5", Installed: false, Version: "1.6.9", ReleaseDate: "2020-08-04", Filename: "ercole-agent-1.6.9-1.x86_64.rpm", Name: "ercole-agent-rhel5", OperatingSystemFamily: "rhel", OperatingSystem: "rhel5", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-rhel5/releases/download/1.6.9/ercole-agent-1.6.9-1.x86_64.rpm"}},
		{Repository: "ercole-agent-virtualization", Installed: false, Version: "1.6.4", ReleaseDate: "2020-02-13", Filename: "ercole-agent-virtualization-1.6.4-1.el7.x86_64.rpm", Name: "ercole-agent-virtualization-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-virtualization/releases/download/1.6.4/ercole-agent-virtualization-1.6.4-1.el7.x86_64.rpm"}},
		{Repository: "ercole-agent-virtualization", Installed: false, Version: "1.6.5", ReleaseDate: "2020-03-11", Filename: "ercole-agent-virtualization-1.6.5-1.el7.x86_64.rpm", Name: "ercole-agent-virtualization-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-virtualization/releases/download/1.6.5/ercole-agent-virtualization-1.6.5-1.el7.x86_64.rpm"}},
	}

	actual := Index{
		&ArtifactInfo{},
		{Repository: "ercole-agent-aix", Installed: false, Version: "1.6.7", ReleaseDate: "2020-01-31", Filename: "ercole-agent-aix-1.6.7.tar.gz", Name: "ercole-agent-aix-targz", OperatingSystemFamily: "aix-tar-gz", OperatingSystem: "aix6.1", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-aix/releases/download/1.6.7/ercole-agent-aix-1.6.7.tar.gz"}},
		{Repository: "ercole-agent-aix", Installed: false, Version: "1.6.8", ReleaseDate: "2020-03-19", Filename: "ercole-agent-aix-1.6.8.tar.gz", Name: "ercole-agent-aix-targz", OperatingSystemFamily: "aix-tar-gz", OperatingSystem: "aix6.1", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-aix/releases/download/1.6.8/ercole-agent-aix-1.6.8.tar.gz"}},
		{Repository: "ercole-agent-aix", Installed: false, Version: "1.6.8", ReleaseDate: "2020-03-19", Filename: "ercole-agent-aix-1.6.8-1.aix6.1.noarch.rpm", Name: "ercole-agent-aix", OperatingSystemFamily: "aix", OperatingSystem: "aix6.1", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-aix/releases/download/1.6.8/ercole-agent-aix-1.6.8-1.aix6.1.noarch.rpm"}},
		{Repository: "ercole-agent-exadata", Installed: false, Version: "1.6.3", ReleaseDate: "2020-03-19", Filename: "ercole-agent-exadata-1.6.3-1.el6.x86_64.rpm", Name: "ercole-agent-exadata-rhel6", OperatingSystemFamily: "rhel", OperatingSystem: "rhel6", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-exadata/releases/download/1.6.3/ercole-agent-exadata-1.6.3-1.el6.x86_64.rpm"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.11", ReleaseDate: "2020-03-27", Filename: "ercole-agent-setup-1.6.11.exe", Name: "ercole-agent-win", OperatingSystemFamily: "win", OperatingSystem: "win", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.11/ercole-agent-setup-1.6.11.exe"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.12", ReleaseDate: "2020-06-08", Filename: "ercole-agent-setup-1.6.12.exe", Name: "ercole-agent-win", OperatingSystemFamily: "win", OperatingSystem: "win", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.12/ercole-agent-setup-1.6.12.exe"}},
		{Repository: "ercole-agent-virtualization", Installed: false, Version: "1.6.5", ReleaseDate: "2020-03-11", Filename: "ercole-agent-virtualization-1.6.5-1.el7.x86_64.rpm", Name: "ercole-agent-virtualization-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-virtualization/releases/download/1.6.5/ercole-agent-virtualization-1.6.5-1.el7.x86_64.rpm"}},
		{Repository: "ercole-agent-exadata", Installed: false, Version: "1.6.2", ReleaseDate: "2020-01-31", Filename: "ercole-agent-exadata-1.6.2-1.el6.x86_64.rpm", Name: "ercole-agent-exadata-rhel6", OperatingSystemFamily: "rhel", OperatingSystem: "rhel6", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-exadata/releases/download/1.6.2/ercole-agent-exadata-1.6.2-1.el6.x86_64.rpm"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.11", ReleaseDate: "2020-03-27", Filename: "ercole-agent-1.6.11-1.el6.x86_64.rpm", Name: "ercole-agent-rhel6", OperatingSystemFamily: "rhel", OperatingSystem: "rhel6", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.11/ercole-agent-1.6.11-1.el6.x86_64.rpm"}},
		{Repository: "ercole-agent-exadata", Installed: false, Version: "1.6.3", ReleaseDate: "2020-03-19", Filename: "ercole-agent-exadata-1.6.3-1.el7.x86_64.rpm", Name: "ercole-agent-exadata-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-exadata/releases/download/1.6.3/ercole-agent-exadata-1.6.3-1.el7.x86_64.rpm"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.12", ReleaseDate: "2020-06-08", Filename: "ercole-agent-1.6.12-1.el6.x86_64.rpm", Name: "ercole-agent-rhel6", OperatingSystemFamily: "rhel", OperatingSystem: "rhel6", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.12/ercole-agent-1.6.12-1.el6.x86_64.rpm"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.11", ReleaseDate: "2020-03-27", Filename: "ercole-agent-1.6.11-1.el7.x86_64.rpm", Name: "ercole-agent-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.11/ercole-agent-1.6.11-1.el7.x86_64.rpm"}},
		{Repository: "ercole-agent-rhel5", Installed: false, Version: "1.6.8", ReleaseDate: "2020-07-28", Filename: "ercole-agent-1.6.8-1.x86_64.rpm", Name: "ercole-agent-rhel5", OperatingSystemFamily: "rhel", OperatingSystem: "rhel5", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-rhel5/releases/download/1.6.8/ercole-agent-1.6.8-1.x86_64.rpm"}},
		{Repository: "ercole-agent-exadata", Installed: false, Version: "1.6.2", ReleaseDate: "2020-01-31", Filename: "ercole-agent-exadata-1.6.2-1.el7.x86_64.rpm", Name: "ercole-agent-exadata-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-exadata/releases/download/1.6.2/ercole-agent-exadata-1.6.2-1.el7.x86_64.rpm"}},
		{Repository: "ercole-agent", Installed: false, Version: "1.6.12", ReleaseDate: "2020-06-08", Filename: "ercole-agent-1.6.12-1.el7.x86_64.rpm", Name: "ercole-agent-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent/releases/download/1.6.12/ercole-agent-1.6.12-1.el7.x86_64.rpm"}},
		{Repository: "ercole-agent-hpux", Installed: false, Version: "1.6.5", ReleaseDate: "2020-01-14", Filename: "ercole-agent-hpux-1.6.5.tar.gz", Name: "ercole-agent-hpux", OperatingSystemFamily: "hpux", OperatingSystem: "hpux", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-hpux/releases/download/1.6.5/ercole-agent-hpux-1.6.5.tar.gz"}},
		{Repository: "ercole-agent-aix", Installed: false, Version: "1.6.0", ReleaseDate: "2019-10-21", Filename: "ercole-agent-aix-1.6.0-1.aix6.1.noarch.rpm", Name: "ercole-agent-aix", OperatingSystemFamily: "aix", OperatingSystem: "aix6.1", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-aix/releases/download/1.6.0/ercole-agent-aix-1.6.0-1.aix6.1.noarch.rpm"}},
		{Repository: "ercole-agent-hpux", Installed: false, Version: "1.6.4", ReleaseDate: "2019-12-16", Filename: "ercole-agent-hpux-1.6.4.tar.gz", Name: "ercole-agent-hpux", OperatingSystemFamily: "hpux", OperatingSystem: "hpux", Arch: "noarch", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-hpux/releases/download/1.6.4/ercole-agent-hpux-1.6.4.tar.gz"}},
		{Repository: "ercole-agent-rhel5", Installed: false, Version: "1.6.9", ReleaseDate: "2020-08-04", Filename: "ercole-agent-1.6.9-1.x86_64.rpm", Name: "ercole-agent-rhel5", OperatingSystemFamily: "rhel", OperatingSystem: "rhel5", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-rhel5/releases/download/1.6.9/ercole-agent-1.6.9-1.x86_64.rpm"}},
		{Repository: "ercole-agent-virtualization", Installed: false, Version: "1.6.4", ReleaseDate: "2020-02-13", Filename: "ercole-agent-virtualization-1.6.4-1.el7.x86_64.rpm", Name: "ercole-agent-virtualization-rhel7", OperatingSystemFamily: "rhel", OperatingSystem: "rhel7", Arch: "x86_64", UpstreamType: "github-release", UpstreamInfo: map[string]interface{}{"DownloadUrl": "https://github.com/ercole-io/ercole-agent-virtualization/releases/download/1.6.4/ercole-agent-virtualization-1.6.4-1.el7.x86_64.rpm"}},
	}

	actual.SortArtifactInfo()

	assert.Equal(t, expected, actual)
}
