insert into license(id, license_count) values('Oracle ENT', 0) on conflict do nothing;
insert into license(id, license_count) values('Oracle STD', 0) on conflict do nothing;
insert into license(id, license_count) values('Oracle EXE', 0) on conflict do nothing;
insert into license(id, license_count) values('WebLogic Server Management Pack Enterprise Edition', 0) on conflict do nothing;
insert into license(id, license_count) values('Tuning Pack', 0) on conflict do nothing;
insert into license(id, license_count) values('Spatial and Graph', 0) on conflict do nothing;
insert into license(id, license_count) values('Secure Backup', 0) on conflict do nothing;
insert into license(id, license_count) values('Real Application Testing', 0) on conflict do nothing;
insert into license(id, license_count) values('Real Application Clusters One Node', 0) on conflict do nothing;
insert into license(id, license_count) values('Real Application Clusters', 0) on conflict do nothing;
insert into license(id, license_count) values('RAC or RAC One Node', 0) on conflict do nothing;
insert into license(id, license_count) values('Provisioning and Patch Automation Pack for Database', 0) on conflict do nothing;
insert into license(id, license_count) values('Provisioning and Patch Automation Pack', 0) on conflict do nothing;
insert into license(id, license_count) values('Pillar Storage', 0) on conflict do nothing;
insert into license(id, license_count) values('Partitioning', 0) on conflict do nothing;
insert into license(id, license_count) values('OLAP', 0) on conflict do nothing;
insert into license(id, license_count) values('Multitenant', 0) on conflict do nothing;
insert into license(id, license_count) values('Label Security', 0) on conflict do nothing;
insert into license(id, license_count) values('HW', 0) on conflict do nothing;
insert into license(id, license_count) values('GoldenGate', 0) on conflict do nothing;
insert into license(id, license_count) values('Exadata', 0) on conflict do nothing;
insert into license(id, license_count) values('Diagnostics Pack', 0) on conflict do nothing;
insert into license(id, license_count) values('Database Vault', 0) on conflict do nothing;
insert into license(id, license_count) values('Database In-Memory', 0) on conflict do nothing;
insert into license(id, license_count) values('Database Gateway', 0) on conflict do nothing;
insert into license(id, license_count) values('Data Masking Pack', 0) on conflict do nothing;
insert into license(id, license_count) values('Configuration Management Pack for Oracle Database', 0) on conflict do nothing;
insert into license(id, license_count) values('Change Management Pack', 0) on conflict do nothing;
insert into license(id, license_count) values('Advanced Security', 0) on conflict do nothing;
insert into license(id, license_count) values('Advanced Compression', 0) on conflict do nothing;
insert into license(id, license_count) values('Advanced Analytics', 0) on conflict do nothing;
insert into license(id, license_count) values('Active Data Guard', 0) on conflict do nothing;
