### Example of LDAP authentication.
### Tested with https://github.com/rroemhild/docker-test-openldap 

[APIService.AuthenticationProvider]
PrivateKey = "/path/to/your/key" # Privatekey is necessary!
Type = "ldap"
Username = "user"
Password = "password"
TokenValidityTimeout = 360
Host = "127.0.0.1"
Port = 10389
LDAPBase = "dc=planetexpress,dc=com"
LDAPBindDN = "cn=admin,dc=planetexpress,dc=com"
LDAPBindPassword = "GoodNewsEveryone"
LDAPUserFilter = "(uid=%s)"
