[DataService]
RemoteEndpoint = "http://127.0.0.1:11111"
BindIP = "0.0.0.0"
Port = 11111
LogHTTPRequest = true
LogInsertingHostdata = false
LogDataPatching = false
EnablePatching = true
AgentUsername = "user"
AgentPassword = "password"

  [DataService.CurrentHostCleaningJob]
  Crontab = "*/1 * * * * *"
  HourThreshold = 1
  RunAtStartup = false

  [DataService.ArchivedHostCleaningJob]
  Crontab = "*/1 * * * * *"
  HourThreshold = 10
  RunAtStartup = false

[AlertService]
RemoteEndpoint = "http://127.0.0.1:11112"
BindIP = "127.0.0.1"
Port = 11112
LogHTTPRequest = true
LogMessages = false
LogAlertThrows = true
PublisherUsername = "publisher"
PublisherPassword = "r4nd0mS3cR3tp4ssW0rd"
QueueBufferSize = 1024

  [AlertService.FreshnessCheckJob]
  Crontab = "*/1 * * * * *"
  DaysThreshold = 1
  RunAtStartup = false

[APIService]
RemoteEndpoint = "http://127.0.0.1:11113"
BindIP = "0.0.0.0"
Port = 11113
LogHTTPRequest = true
ReadOnly = false
EnableInsertingCustomPatchingFunction = true

  [APIService.AuthenticationProvider]
  Type = "basic"
  Username = "user"
  Password = "password"
  PrivateKey = "/etc/ssh/ssh_host_rsa_key"
  PublicKey = "/etc/ssh/ssh_host_rsa_key.pub"
  TokenValidityTimeout = 2700

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^Red Hat Enterprise Linux 8.*$"
  Group = "RHEL8"
  Product = "RedHat/EnterpriseLinux8"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^Red Hat Enterprise Linux 7.*$"
  Group = "RHEL7"
  Product = "RedHat/EnterpriseLinux7"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^Red Hat Enterprise Linux 6.*$"
  Group = "RHEL6"
  Product = "RedHat/EnterpriseLinux6"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^Red Hat Enterprise Linux 5.*$"
  Group = "RHEL5"
  Product = "RedHat/EnterpriseLinux5"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^HPUX.*$"
  Group = "HPUX"
  Product = "HP/HPUX"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^AIX.*$"
  Group = "AIX"
  Product = "IBM/AIX"

  [[APIService.OperatingSystemAggregationRules]]
  Regex = "^Solaris .*$"
  Group = "Solaris"
  Product = "Oracle/Solaris"

[ChartService]
RemoteEndpoint = "http://127.0.0.1:11116"
BindIP = "0.0.0.0"
Port = 11116
LogHTTPRequest = true

[RepoService]

  [RepoService.HTTP]
  Enable = true
  RemoteEndpoint = "http://127.0.0.1:11114"
  BindIP = "0.0.0.0"
  Port = 11114
  LogHTTPRequest = true

  [RepoService.SFTP]
  Enable = true
  RemoteEndpoint = "sftp://127.0.0.1:11115"
  BindIP = "0.0.0.0"
  Port = 11115
  PrivateKey = "/etc/ssh/ssh_host_rsa_key"
  LogConnections = true
  DebugConnections = false

  [[RepoService.UpstreamRepositories]]
  Name = "ercole-agent"
  Type = "github-release"
  URL = "https://api.github.com/repos/ercole-io/ercole-agent/releases"

  [[RepoService.UpstreamRepositories]]
  Name = "ercole-agent-rhel5"
  Type = "github-release"
  URL = "https://api.github.com/repos/ercole-io/ercole-agent-rhel5/releases"

  [[RepoService.UpstreamRepositories]]
  Name = "ercole-agent-aix"
  Type = "github-release"
  URL = "https://api.github.com/repos/ercole-io/ercole-agent-aix/releases"

  [[RepoService.UpstreamRepositories]]
  Name = "ercole-agent-hpux"
  Type = "github-release"
  URL = "https://api.github.com/repos/ercole-io/ercole-agent-hpux/releases"

  [[RepoService.UpstreamRepositories]]
  Name = "ercole-agent-exadata"
  Type = "github-release"
  URL = "https://api.github.com/repos/ercole-io/ercole-agent-exadata/releases"

  [[RepoService.UpstreamRepositories]]
  Name = "ercole-agent-virtualization"
  Type = "github-release"
  URL = "https://api.github.com/repos/ercole-io/ercole-agent-virtualization/releases"
  
[Mongodb]
URI = "mongodb://localhost:27017/ercole"
DBName = "ercole"
Migrate = false